### ISSUE TITLE
Create Readme.md

### ISSUE THREAD

**Issue by ayushsarode** [ayushsarode/HacktoberFest2023-Profile-Card#1]
Add readme.md file. 
Sections we need - 
1.  Introduction
2. Contributing (redirect to contributing.md)
3. License
4. author
5. Contributors 

Also If you have ideas on how we can improve the docs, Suggest us!
Thank you!

**Comment by IndranjanaChatterjee** [comment]
I would like to contribute in this issue. Please assign this to me
